version: '3.0'

services:
  # orders:
  #   build:
  #     context: .
  #     dockerfile: ./apps/orders/Dockerfile
  #     target: development
  #   command: npm run start:dev orders
  #   env_file:
  #     - ./apps/orders/.env
  #   depends_on:
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-arbiter
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3000:3000'

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

# volumes:
#   mongodb_master_data:
#     driver: local
